const fs = require('fs');
const path = require('path');

const baseDir = 'Electronics-2/questions_data';
const outputJsPath = 'Electronics-2/calc-questions.js';

if (!fs.existsSync(baseDir)) {
    console.error("Folder not found: " + baseDir);
    process.exit(1);
}

const CALC_QUESTIONS = {};

// Hardcode or dynamically generate the meta. For now, keep the existing meta format.
const CALC_TOPIC_META = {
    lec1: { name: "DC Transistor Analysis", icon: "🔋", sheet: "Lecture 1" },
    lec2: { name: "Small-Signal BJT Amplifiers", icon: "📐", sheet: "Lecture 2" },
    lec3: { name: "FET Small-Signal Analysis", icon: "⚡", sheet: "Lecture 3" },
    lec4: { name: "FET Configurations", icon: "🔧", sheet: "Lecture 4" },
    lec6: { name: "Op-Amp Analysis", icon: "🎛️", sheet: "Lecture 6" },
    lec7: { name: "Op-Amp Applications", icon: "📊", sheet: "Lecture 7" }
};

const chapters = fs.readdirSync(baseDir).filter(f => fs.statSync(path.join(baseDir, f)).isDirectory());

chapters.forEach(ch => {
    const lecKey = ch.replace('ch', 'lec'); // map ch1 -> lec1
    CALC_QUESTIONS[lecKey] = [];
    
    // Create meta entry if it doesn't exist
    if (!CALC_TOPIC_META[lecKey]) {
        CALC_TOPIC_META[lecKey] = { name: "Chapter " + ch.replace('ch', ''), icon: "📝", sheet: ch.toUpperCase() };
    }

    const chPath = path.join(baseDir, ch);
    const questions = fs.readdirSync(chPath).filter(f => fs.statSync(path.join(chPath, f)).isDirectory());
    
    // Sort questions numerically
    questions.sort((a, b) => parseInt(a) - parseInt(b));

    questions.forEach(qNum => {
        const qPath = path.join(chPath, qNum);
        
        const qObj = {
            id: `written_${ch}_${qNum}`,
            title: `Question ${qNum}`,
            description: "",
            questionImg: "",
            solutionImgs: [],
            fields: []
        };

        // Find question image
        const files = fs.readdirSync(qPath);
        const qFile = files.find(f => f.startsWith('question.'));
        if (qFile) {
            // Keep the path relative to the root for the browser
            qObj.questionImg = `Electronics-2/questions_data/${ch}/${qNum}/${qFile}`;
        }

        // Find answer images
        const aFiles = files.filter(f => f.startsWith('answer.') || f.startsWith('answer1.') || f.startsWith('answer2.'));
        aFiles.sort(); // Sort so answer1 comes before answer2
        aFiles.forEach(aFile => {
            qObj.solutionImgs.push(`Electronics-2/questions_data/${ch}/${qNum}/${aFile}`);
        });

        // Parse fields.txt
        const fieldsPath = path.join(qPath, 'fields.txt');
        if (fs.existsSync(fieldsPath)) {
            const lines = fs.readFileSync(fieldsPath, 'utf8').split('\n');
            
            let parsingFields = false;
            
            lines.forEach(line => {
                const text = line.trim();
                if (!text) return;
                
                if (text.startsWith('Title:')) {
                    qObj.title = text.replace('Title:', '').trim();
                } else if (text.startsWith('Description:')) {
                    qObj.description = text.replace('Description:', '').trim();
                } else if (text.startsWith('Fields:')) {
                    parsingFields = true;
                } else if (parsingFields) {
                    // Expecting: Label | Unit | Answer | Tolerance
                    const parts = text.split('|').map(p => p.trim());
                    if (parts.length >= 3) {
                        qObj.fields.push({
                            label: parts[0],
                            unit: parts[1] || "",
                            answer: parseFloat(parts[2]),
                            tolerance: parseFloat(parts[3] || "0")
                        });
                    }
                }
            });
        }
        
        CALC_QUESTIONS[lecKey].push(qObj);
    });
});

let outputJs = `// ============================================================
// AUTO-GENERATED FILE
// Do not edit this file directly! 
// Edit the files in Electronics-2/questions_data/ and run build_questions.bat
// ============================================================

var CALC_QUESTIONS = ${JSON.stringify(CALC_QUESTIONS, null, 2)};

var CALC_TOPIC_META = ${JSON.stringify(CALC_TOPIC_META, null, 2)};
`;

fs.writeFileSync(outputJsPath, outputJs, 'utf8');
console.log("Successfully rebuilt calc-questions.js from the folder structure!");
